### ISSUE TITLE
支持vuepress-reco2.x吗？

### ISSUE THREAD

**Issue by jinhan52** [vuepress-reco/vuepress-plugin-bgm-player#6]
在使用vuepress-theme-reco2.x的时候，配置语法错误，请问在2.x里面怎么用啊

**Comment by threeTrave** [comment]
同问

**Comment by threeTrave** [comment]
> 在使用vuepress-theme-reco2.x的时候，配置语法错误，请问在2.x里面怎么用啊

可以看下最新的issue，我已经指出了，另外在构建时也会有一些小问题。我待会写进issue

**Comment by threeTrave** [comment]
https://github.com/threeTrave/vuepress-plugin-bgm-player2x 我对reco2做的一个适配版本，（：
